// Generated by Makefile. Keep the original C files included,
// and map the synthesized wrapper back to upstream source lines.
#include "adams_bridge_dilithium_ref/params.h"
#include "adams_bridge_dilithium_ref/reduce.c"
#undef DILITHIUM_NAMESPACE
#define DILITHIUM_NAMESPACE(s) xlscc_original_##s
#include "adams_bridge_dilithium_ref/reduce.c"
#include "adams_bridge_dilithium_ref/ntt.c"
#undef ntt
#undef invntt_tomont
#undef DILITHIUM_NAMESPACE
#ifdef DILITHIUM_USE_AES
#if DILITHIUM_MODE == 2
#define DILITHIUM_NAMESPACE(s) pqcrystals_dilithium2aes_ref_##s
#elif DILITHIUM_MODE == 3
#define DILITHIUM_NAMESPACE(s) pqcrystals_dilithium3aes_ref_##s
#elif DILITHIUM_MODE == 5
#define DILITHIUM_NAMESPACE(s) pqcrystals_dilithium5aes_ref_##s
#endif
#else
#if DILITHIUM_MODE == 2
#define DILITHIUM_NAMESPACE(s) pqcrystals_dilithium2_ref_##s
#elif DILITHIUM_MODE == 3
#define DILITHIUM_NAMESPACE(s) pqcrystals_dilithium3_ref_##s
#elif DILITHIUM_MODE == 5
#define DILITHIUM_NAMESPACE(s) pqcrystals_dilithium5_ref_##s
#endif
#endif
#line 49 "src/adams_bridge_dilithium_ref/ntt.c"
void DILITHIUM_NAMESPACE(ntt)(int32_t a[N]) {
#line 50 "src/adams_bridge_dilithium_ref/ntt.c"
  unsigned int len, start, j, k;
#line 51 "src/adams_bridge_dilithium_ref/ntt.c"
  int32_t zeta, t;
#line 53 "src/adams_bridge_dilithium_ref/ntt.c"
  k = 0;
#line 54 "src/adams_bridge_dilithium_ref/ntt.c"
#pragma hls_unroll yes
#line 54 "src/adams_bridge_dilithium_ref/ntt.c"
  for(len = 128; len > 0; len >>= 1) {
#line 55 "src/adams_bridge_dilithium_ref/ntt.c"
#pragma hls_unroll yes
#line 55 "src/adams_bridge_dilithium_ref/ntt.c"
    for(start = 0; start < N; start = j + len) {
#line 56 "src/adams_bridge_dilithium_ref/ntt.c"
      zeta = zetas[++k];
#line 57 "src/adams_bridge_dilithium_ref/ntt.c"
#pragma hls_unroll yes
#line 57 "src/adams_bridge_dilithium_ref/ntt.c"
      for(j = start; j < start + len; ++j) {
#line 58 "src/adams_bridge_dilithium_ref/ntt.c"
        t = montgomery_reduce((int64_t)zeta * a[j + len]);
#line 59 "src/adams_bridge_dilithium_ref/ntt.c"
        a[j + len] = a[j] - t;
#line 60 "src/adams_bridge_dilithium_ref/ntt.c"
        a[j] = a[j] + t;
#line 61 "src/adams_bridge_dilithium_ref/ntt.c"
      }
#line 62 "src/adams_bridge_dilithium_ref/ntt.c"
    }
#line 63 "src/adams_bridge_dilithium_ref/ntt.c"
  }
#line 64 "src/adams_bridge_dilithium_ref/ntt.c"
}
