format: systemverilog
verification: sec
max_k: 4
sv_design1_top: pqcrystals_dilithium5_ref_ntt
sv_design2_top: pqcrystals_dilithium5_ref_ntt
input_paths:
  - ./generated/design1_ntt_xlscc.sv
  - ./generated/design2_ntt_xlscc.sv
